# Generated by Django 3.2 on 2021-04-25 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroDeProdutos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Produto')),
                ('dataCadastro', models.DateField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cadastro de Produto',
                'verbose_name_plural': 'Cadastro de Produtos',
            },
        ),
        migrations.CreateModel(
            name='CompraDeProdutos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=0, verbose_name='Quantidade')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('dataCompra', models.DateField(auto_now_add=True, verbose_name='Data de Compra')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cadastrodeprodutos', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Compra de Produto',
                'verbose_name_plural': 'Compra de Produtos',
            },
        ),
    ]
