# Generated by Django 3.2 on 2021-04-26 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compradeprodutos',
            name='preco_medio',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Preço Medio de Compra'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compradeprodutos',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade'),
        ),
    ]
