# Generated by Django 3.2 on 2021-04-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0002_auto_20210426_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compradeprodutos',
            name='preco_medio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Medio de Compra'),
        ),
    ]
